### Step 1: Create a Customer
PUT http://localhost:8080/customers
Content-Type: application/json

{
  "userName": "customer",
  "email": "customer@gmail.com",
  "password": "1234"
}

### Step 2: Get a Customer
GET http://localhost:8080/customers/31b5c2b8-e19e-4658-b2f1-a7fe8def2549
Content-Type: application/json