### Step 1: Create a Customer
PUT http://localhost:8080/customers
Content-Type: application/json

{
  "userName": "customer",
  "email": "customer@gmail.com",
  "password": "1234"
}

### Step 2: Get a Customer
GET http://localhost:8080/customers/90d50a32-3849-42d3-9c8f-d2e68523336b
Content-Type: application/json