### Credit
PUT http://localhost:8080/transfers/credit
Content-Type: application/json

{
  "walletId": "c9a7ff38-92f9-40b7-a457-1986ded92ba8",
  "amount": "20"
}

### Debit
PUT http://localhost:8080/transfers/debit
Content-Type: application/json

{
  "walletId": "c9a7ff38-92f9-40b7-a457-1986ded92ba8",
  "amount": "-10"
}

