### Credit
PUT http://localhost:8080/transfers/credit
Content-Type: application/json

{
  "walletId": "4fa48f2c-0a1d-4202-aa0a-befe8a61716c",
  "amount": "40"
}

### Debit
PUT http://localhost:8080/transfers/debit
Content-Type: application/json

{
  "walletId": "4fa48f2c-0a1d-4202-aa0a-befe8a61716c",
  "amount": "-10"
}

