### Step 3: Create a wallet
PUT http://localhost:8080/wallets
Content-Type: application/json

{
  "customerId": "0644fb79-6d75-42e4-bef2-17c199e8836d"
}

### Step 4: Visualize a Wallet
GET http://localhost:8080/wallets/4fa48f2c-0a1d-4202-aa0a-befe8a61716c
Accept: application/json

### Visualize a Wallet with transfers
GET http://localhost:8080/wallet/4fa48f2c-0a1d-4202-aa0a-befe8a61716c/transfers

