### Step 3: Create a wallet
PUT http://localhost:8080/wallets
Content-Type: application/json

{
  "customerId": "31b5c2b8-e19e-4658-b2f1-a7fe8def2549"
}

### Step 4: Visualize a Wallet
GET http://localhost:8080/wallets/c9a7ff38-92f9-40b7-a457-1986ded92ba8
Accept: application/json

### Visualize a Wallet with transfers
GET http://localhost:8080/wallet/c9a7ff38-92f9-40b7-a457-1986ded92ba8/transfers

