###
PUT http://localhost:8080/customers
Content-Type: application/json

{
  "userName": "xxx",
  "email": "customer@gmail.com",
  "password": "1234"
}

###
GET http://localhost:8080/customers/3eca748e-76d0-4dd2-8cf7-25d640c7d067
Content-Type: application/json