
### Create a wallet

POST http://localhost:8080/wallet
Content-Type: application/json

{
  "userId": "{{$uuid}}"
}

### Visualize a Wallet
GET http://localhost:8080/wallet?id={{$uuid}}
Accept: application/json

### Deposit
POST http://localhost:8080/wallet/deposit
Content-Type: application/json

{
  "walletId": "{{$uuid}}",
  "source": "IBAN",
  "concept": "",
  "amount": "{{$randomInt}}",
  "currency": "978"
}

### Transfer
POST http://localhost:8080/wallet/transfer
Content-Type: application/json

{
  "walletId": "{{$uuid}}",
  "destination": "IBAN",
  "concept": "",
  "amount": "{{$randomInt}}",
  "currency": "978"
}