
### Create a wallet
PUT http://localhost:8080/wallets
Content-Type: application/json

{
  "userId": "{{$uuid}}"
}


### Visualize a Wallet
GET http://localhost:8080/wallets/{{$uuid}}
Accept: application/json

### Deposit
PUT http://localhost:8080/wallets/deposit
Content-Type: application/json

{
  "walletId": "{{$uuid}}",
  "source": "IBAN",
  "concept": "",
  "amount": "{{$randomInt}}",
  "currency": "978"
}

### Transfer
PUT http://localhost:8080/wallets/transfer
Content-Type: application/json

{
  "walletId": "{{$uuid}}",
  "destination": "IBAN",
  "concept": "",
  "amount": "{{$randomInt}}",
  "currency": "978"
}